# workaroud for toml schema until https://github.com/air-verse/air/pull/743 is merged
#:schema https://raw.githubusercontent.com/air-verse/air/0a3f56961f682c08c2d012dbf828188b4e12e854/air.schema.json
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "tmp/server.exe"
cmd = "go build -o ./tmp/server.exe ./cmd/server/."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "dlv exec --listen=127.0.0.1:2345 --headless=true --api-version=2 --accept-multiclient --continue --log ./tmp/server.exe"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = 0
log = "build-errors.log"
poll = false
poll_interval = 500
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false


[screen]
clear_on_rebuild = false
keep_scroll = true
